---
- name: Check and Reboot Ubuntu VM if needed
  hosts: "{{ target_hosts }}"
  become: true
  tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the machine if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible because a reboot is required"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
